<template>
  <!-- 會計系統 -->
  <section class="Acntsys">
    <section class="landing-acntsys">
      <div class="img" title="會計管理系統"></div>
      <h1 class="title">會計管理系統</h1>
    </section>
    <div class="mx-auto">
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC1.svg"
        alt="系統功能，每日傳票作業流程圖，月結帳及報表，轉帳傳票及其他，發票折讓退回證明單(由傳票擷取)"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC2.svg"
        alt="發票折讓退回證明單(由傳票擷取)，傳票列印預覽功能，日記帳查詢及預覽列印，公司別或專案別或對象(廠商)別分類帳"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC3.svg"
        alt="公司別或組織別試算表，公司別或組織別費用比較表，立沖帳查詢及預覽列印:立沖分類帳表，立沖餘額明細表。應收票據(轉EXCEL):應收票據明細表，應付票據明細表。資產負債表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC4.svg"
        alt="資產負載表，明細資產負債表，組織別資產負債表(可依公司下之各部門或專案編制)"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC5.svg"
        alt="公司合併資產負債表(可做多家公司合併之報表)，損益表查詢印表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC6.svg"
        alt="損益表二【月結後】，損益表查詢印表【組織別】，各案收支彙總表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC7.svg"
        alt="收入/支出彙總表，各案收支明細表，損益認列收入成本分析表，完工比例法工程損益計算明細表【各月比較表】"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC8.svg"
        alt="完工比例法工程損益計算明細表【年度比較表】，工程分析明細表，收入成本估計表，在建工程明細表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC9.svg"
        alt="公司別在建工程彙總表，在建工程彙總表【原物料】，在建工程及預收工程款比較分析表，工程款收入明細表，工程款收入彙總表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC10.svg"
        alt="已完工工程成本分析表，未完工程成本分析表，在建工程及期末在建工程明細表，案別材料進耗存明細表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC11.svg"
        alt="公司別料進耗存明細表，總分類帳，試算表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC12.svg"
        alt="試算表，明細試算表，明細試算表【公司別】"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC13.svg"
        alt="明細試算EXCEL表【公司別】，管銷費用排行表，每月費用比較表(半年報)，每月費用比較表(年報)"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC14.svg"
        alt="分類帳餘額表，分類帳餘額EXCEL表，組織別費用分析表，各按別科目彙總表，付款彙總表【傳票主檔】，客戶繳款彙總表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC15.svg"
        alt="帳號科目餘額明細表:帳號餘額明細表。工程成本及期末在建工程明細表"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC16.svg"
        alt="完工工程成本分析表，未完工程分析表，公司別各案損益表彙總表，營造用【損益表】，營造用【資產負債表】，建設用【損益表】，建設用【資產負債表】"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC17.svg"
        alt="工程收入明細表，在建工程及預收工程款比較分析表，傳票自動編好(適合多人使用)，立沖帳可當日沖銷功能"
      />
      <img
        class="page-svg"
        src="@/assets/svg/AC/AC18.svg"
        alt="分類帳查詢功能，工程分析明細表，工程損益認列可調整估計尚須成本且自動重新計算相關金額，固定資產、拆舊計算，"
      />
    </div>
  </section>
</template>
